CREATE TABLE `gitmr` (
        `ID` INT(11) NOT NULL AUTO_INCREMENT,
        `COMMIT` VARCHAR(65536) NOT NULL,
        `BRANCHE` VARCHAR(65536) NOT NULL,
        `SORT` INT(11) DEFAULT 500,
        `USER_ID` VARCHAR(100),
        `MR_ID` VARCHAR(100),
        `MR_DATE` VARCHAR(100),
        `TYPE` VARCHAR(100),
        `CREATED` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY(ID)
    );